# Build commands
[build]
    base = ""
    publish = "www"

# Redirect rules
[[redirects]]
    from = "http://www.wedgwooddesign.co.uk/*"
    to = "http://wedgwooddesign.com/:splat"

[[redirects]]
    from = "http://wedgwooddesign.netlify.com/*"
    to = "http://wedgwooddesign.com/:splat"
